GET http://localhost:8080/auction?status=0&category=Auto&productName=Fiat
Content-Type: application/json
Accept: application/json

###

POST http://localhost:8080/auction
Content-Type: application/json
Accept: application/json

{
  "product_name": "Celular",
  "category": "Eletrônicos",
  "description": "Lote de aparelhos celulares",
  "condition": 0
}

###

POST http://localhost:8080/auction
Content-Type: application/json
Accept: application/json

{
  "product_name": "Fiat Marea",
  "category": "Auto",
  "description": "Veículos top",
  "condition": 2
}

###

GET http://localhost:8080/auction/d281bdfa-4e61-47df-91d3-fa977407f1fa
Content-Type: application/json
