POST http://localhost:8080/auction
Content-Type: application/json
Accept: application/json

{
  "product_name": "Celular",
  "category": "Eletrônicos",
  "description": "Lote de aparelhos celulares",
  "condition": 0
}

###

POST http://localhost:8080/auction
Content-Type: application/json
Accept: application/json

{
  "product_name": "Notebook",
  "category": "Eletrônicos",
  "description": "Lote de aparelhos eletrônicos",
  "condition": 0
}

###

POST http://localhost:8080/auction
Content-Type: application/json
Accept: application/json

{
  "product_name": "Fiat Uno",
  "category": "Auto",
  "description": "Lote de Veículos",
  "condition": 2
}

###

POST http://localhost:8080/auction
Content-Type: application/json
Accept: application/json

{
  "product_name": "Chevrolet Classic",
  "category": "Auto",
  "description": "Lote de Veículos",
  "condition": 2
}

###

GET http://localhost:8080/auction?status=0&category=Auto&productName=Fiat
Content-Type: application/json
Accept: application/json

###

GET http://localhost:8080/auction/winner/fb479b90-c20c-463f-be90-abd8b3b24255
Content-Type: application/json
Accept: application/json

###

GET http://localhost:8080/auction/d281bdfa-4e61-47df-91d3-fa977407f1fa
Content-Type: application/json
