POST http://localhost:8080/bid
Accept: application/json
Content-Type: application/json

{
  "user_id": "94792521-3cf4-4221-8d4b-ceef797d32e2",
  "auction_id": "d6b3a36c-f855-41f9-846e-fad96c91b993",
  "amount":  1001
}

###

POST http://localhost:8080/bid
Accept: application/json
Content-Type: application/json

{
  "user_id": "ccfca080-4d5c-4d12-871d-8acafee8206e",
  "auction_id": "d6b3a36c-f855-41f9-846e-fad96c91b993",
  "amount":  1006
}

###

POST http://localhost:8080/bid
Accept: application/json
Content-Type: application/json

{
  "user_id": "94792521-3cf4-4221-8d4b-ceef797d32e2",
  "auction_id": "d6b3a36c-f855-41f9-846e-fad96c91b993",
  "amount":  1500
}

###

POST http://localhost:8080/bid
Accept: application/json
Content-Type: application/json

{
  "user_id": "ccfca080-4d5c-4d12-871d-8acafee8206e",
  "auction_id": "d6b3a36c-f855-41f9-846e-fad96c91b993",
  "amount":  1900
}

###

GET http://localhost:8080/bid/d6b3a36c-f855-41f9-846e-fad96c91b993
Accept: application/json
Content-Type: application/json